# -*- coding: utf-8 -*-
"""model_training.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O4RSce3lT9VgpdCcJsBwjA-z_ztDMPfq
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import joblib

# Load dataset
df = pd.read_csv("/content/sample_data/student_performance_15cols_100x100.csv")

# Split Features and Target
X = df.drop(columns=['performance'])
y = df['performance']

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train Model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Save Model
joblib.dump(model, 'edu_model.pkl')
print("Model saved as edu_model.pkl")