# -*- coding: utf-8 -*-
"""RequestHandler.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KFbeQLgpJaTTUQJGJoTOlu7Yr6O5UuEL
"""

import requests

API_URL = "https://your-render-api-url.com/predict"  # ✅ Replace with correct URL

def send_prediction_request(input_features):
    """Sends a POST request to the prediction API with input features."""
    try:
        response = requests.post(API_URL, json={"features": input_features}, timeout=10)
        response.raise_for_status()
        return response.json()
    except requests.ConnectionError:
        return {"error": "Unable to connect. Check API URL and internet connection."}
    except requests.Timeout:
        return {"error": "Server is taking too long to respond. Try again later."}
    except requests.RequestException as e:
        return {"error": f"Request failed: {str(e)}"}